from pydantic import Field, BaseModel
from typing import Optional, Literal

from app.models.llm_content_block import LLMContentBlock
from app.models.llm_tool_call import LLMToolCall

LLMRole = Literal[
    "user",
    "assistant",
    "system",
    "tool"
]

class LLMMessage(BaseModel):

    content: str = Field(
        description="The contents of the user message."
    )

    content_blocks: list[LLMContentBlock] = Field(
        default_factory=list,
        description="One piece of content within the conversation event. A single message "
                    "can contain text, images, audio, and file attachments."
    )

    role: Optional[LLMRole] = Field(
        default="user",
        description="The role of the messages author. Can be `user`, `assistant`, `system` or `tool`."
    )

    name: Optional[str] = Field(
        default=None,
        description="An optional name for the participant. Provides the model information to "
                    "differentiate between participants of the same role."
    )

    tool_calls: Optional[list[LLMToolCall]] = Field(
        default=None,
        description="The tool calls generated by the model/llm, such as function calls."
    )

    tool_call_id: Optional[str] = Field(
        default=None,
        description="Tool call that this message is responding to."
    )